language: php

before_script:
    composer install

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit
